# Each session maps to a list of exercise dicts.
# Keys: name, muscle, minutes, sets_reps, equipment, difficulty, steps (list), tip

EXERCISES = {

    # ── MUSCLE & STRENGTH ─────────────────────────────────────────────────────

    "Upper Push": [
        {
            "name": "Treadmill Warm-Up",
            "muscle": "Full Body Warm-Up",
            "minutes": 10,
            "sets_reps": "10 min continuous",
            "equipment": "Treadmill",
            "difficulty": "Beginner",
            "steps": [
                "Start at a comfortable walking pace (4–5 km/h)",
                "Gradually increase to a light jog over 5 minutes",
                "Keep arms swinging naturally, breathe steadily",
                "Last 2 minutes: return to walking to transition into lifting",
            ],
            "tip": "Never skip your warm-up. 10 minutes of light cardio raises your core temperature and primes your muscles for heavier work.",
        },
        {
            "name": "Barbell Bench Press",
            "muscle": "Chest · Shoulders · Triceps",
            "minutes": 15,
            "sets_reps": "3 sets × 8–10 reps",
            "equipment": "Barbell, Bench, Rack",
            "difficulty": "Beginner",
            "steps": [
                "Lie flat on the bench, grip bar just wider than shoulder-width",
                "Unrack the bar and hold it directly above your chest",
                "Lower bar slowly to mid-chest — elbows at about 45° angle",
                "Drive the bar back up explosively until arms are extended",
                "Keep feet flat, back slightly arched, core braced throughout",
            ],
            "tip": "Start with just the barbell (20 kg) to practise form. A spotter is highly recommended!",
        },
        {
            "name": "Dumbbell Shoulder Press",
            "muscle": "Shoulders · Triceps",
            "minutes": 12,
            "sets_reps": "3 sets × 10–12 reps",
            "equipment": "Dumbbells, Adjustable Bench",
            "difficulty": "Beginner",
            "steps": [
                "Sit on an upright bench, dumbbells at shoulder height, palms forward",
                "Press dumbbells overhead in a controlled arc until arms are straight",
                "Don't fully lock out elbows — keep a slight bend at the top",
                "Lower dumbbells slowly back to shoulder height and repeat",
            ],
            "tip": "Keep your lower back pressed into the bench. Arching excessively puts strain on your spine.",
        },
        {
            "name": "Cable Tricep Pushdown",
            "muscle": "Triceps",
            "minutes": 10,
            "sets_reps": "3 sets × 12 reps",
            "equipment": "Cable Machine, Straight or Rope Attachment",
            "difficulty": "Beginner",
            "steps": [
                "Set the cable pulley to head height and attach a straight bar or rope",
                "Grip the attachment, tuck elbows tight to your sides",
                "Push handle straight down until arms are fully extended",
                "Slowly return to start — elbows must NOT move forward or back",
            ],
            "tip": "The key is keeping elbows stationary at your sides. If they fly forward, the weight is too heavy.",
        },
        {
            "name": "Dumbbell Chest Fly",
            "muscle": "Chest (Outer)",
            "minutes": 10,
            "sets_reps": "3 sets × 12 reps",
            "equipment": "Dumbbells, Flat Bench",
            "difficulty": "Beginner",
            "steps": [
                "Lie on a flat bench, hold dumbbells above chest with slight elbow bend",
                "Open arms wide in a large arc, feeling a deep chest stretch at the bottom",
                "Squeeze your chest to bring dumbbells back together at the top",
                "Maintain the slight elbow bend throughout — never fully straighten arms",
            ],
            "tip": "Think of hugging a large tree. Avoid letting the dumbbells drop too low — shoulder height is your limit.",
        },
        {
            "name": "Cool Down & Stretching",
            "muscle": "Full Body",
            "minutes": 8,
            "sets_reps": "8 min — hold each stretch 30s",
            "equipment": "Exercise Mat",
            "difficulty": "Beginner",
            "steps": [
                "Chest doorway stretch: 30 seconds each side",
                "Tricep overhead stretch: 30 seconds each arm",
                "Shoulder cross-body stretch: 30 seconds each",
                "Seated forward fold for back and hamstrings: 60 seconds",
            ],
            "tip": "Static stretching after training improves flexibility and reduces next-day soreness. Don't rush this!",
        },
    ],

    "Lower A": [
        {
            "name": "Dynamic Warm-Up",
            "muscle": "Legs & Hips",
            "minutes": 8,
            "sets_reps": "2 rounds of circuit",
            "equipment": "None",
            "difficulty": "Beginner",
            "steps": [
                "10 × Leg swings (front-to-back) each leg",
                "10 × Hip circles each direction",
                "10 × Bodyweight squats (slow and controlled)",
                "10 × Walking lunges across the room",
            ],
            "tip": "Dynamic warm-ups activate your hip flexors and glutes — essential before heavy leg work.",
        },
        {
            "name": "Barbell Squat",
            "muscle": "Quads · Glutes · Hamstrings",
            "minutes": 18,
            "sets_reps": "3 sets × 8–10 reps",
            "equipment": "Barbell, Squat Rack",
            "difficulty": "Intermediate",
            "steps": [
                "Set bar at shoulder height in the rack; step under and rest it on your traps",
                "Feet shoulder-width apart, toes turned out slightly",
                "Take a deep breath, brace your core, then sit down and back",
                "Squat until thighs are parallel to the floor (or below)",
                "Drive through your heels to stand back up — chest stays up throughout",
            ],
            "tip": "Beginners: start with just the bar and practise the movement for 2 weeks before adding plates.",
        },
        {
            "name": "Leg Press Machine",
            "muscle": "Quads · Glutes",
            "minutes": 14,
            "sets_reps": "3 sets × 10–12 reps",
            "equipment": "Leg Press Machine",
            "difficulty": "Beginner",
            "steps": [
                "Adjust the seat so knees bend to ~90° at the bottom",
                "Place feet shoulder-width on the platform",
                "Release safety handles and lower the plate toward you in control",
                "Push through your heels until legs are nearly (not fully) extended",
                "Re-engage the safety handles between sets",
            ],
            "tip": "Perfect for beginners — the machine guides your movement so you can focus on building quad strength safely.",
        },
        {
            "name": "Romanian Deadlift (RDL)",
            "muscle": "Hamstrings · Glutes",
            "minutes": 14,
            "sets_reps": "3 sets × 10 reps",
            "equipment": "Barbell or Dumbbells",
            "difficulty": "Intermediate",
            "steps": [
                "Stand holding a bar at hip height, feet hip-width, soft knee bend",
                "Hinge at the hips — push them BACK, not down",
                "Let the bar slide down your legs until you feel a hamstring stretch",
                "Drive hips forward to return upright — squeeze glutes at the top",
                "Keep your back flat and shoulders pulled back throughout",
            ],
            "tip": "Imagine closing a car door with your bum — that hip-hinge pattern is exactly what you need.",
        },
        {
            "name": "Leg Curl Machine",
            "muscle": "Hamstrings",
            "minutes": 10,
            "sets_reps": "3 sets × 12 reps",
            "equipment": "Lying Leg Curl Machine",
            "difficulty": "Beginner",
            "steps": [
                "Lie face down, position the pad just above your heels",
                "Curl legs upward as far as possible without lifting your hips",
                "Squeeze hamstrings hard at the top for 1 second",
                "Lower slowly over 3 seconds — the eccentric phase builds the most muscle",
            ],
            "tip": "The slow lowering phase (eccentric) is where most muscle growth happens. Don't just drop the weight!",
        },
        {
            "name": "Cool Down & Stretching",
            "muscle": "Legs & Hips",
            "minutes": 8,
            "sets_reps": "8 min",
            "equipment": "Exercise Mat",
            "difficulty": "Beginner",
            "steps": [
                "Standing quad stretch: 30 seconds each leg",
                "Seated hamstring stretch (both legs): 60 seconds",
                "Pigeon pose for glutes: 45 seconds each side",
                "Calf stretch against wall: 30 seconds each",
            ],
            "tip": "Tight hips and hamstrings are the #1 cause of lower back pain. Stretch every single session!",
        },
    ],

    "Upper Pull": [
        {
            "name": "Rowing Machine Warm-Up",
            "muscle": "Back, Arms & Core",
            "minutes": 8,
            "sets_reps": "8 min steady pace",
            "equipment": "Rowing Machine",
            "difficulty": "Beginner",
            "steps": [
                "Strap feet in, grip the handle with an overhand grip",
                "Push with legs first, then lean back slightly, then pull arms in",
                "Reverse the sequence to return: arms extend, lean forward, legs bend",
                "Keep a consistent rhythm — aim for 20–24 strokes per minute",
            ],
            "tip": "The rowing machine warms up your entire back and arms — perfect prep for a pull day!",
        },
        {
            "name": "Lat Pulldown",
            "muscle": "Lats · Upper Back",
            "minutes": 14,
            "sets_reps": "3 sets × 10–12 reps",
            "equipment": "Lat Pulldown Machine",
            "difficulty": "Beginner",
            "steps": [
                "Sit and adjust the knee pad to secure your legs",
                "Grip the bar wider than shoulder-width, overhand grip",
                "Lean back slightly and pull bar to your upper chest",
                "Lead with your elbows — imagine tucking them into your back pockets",
                "Let the bar rise slowly with full arm extension between reps",
            ],
            "tip": "Think 'elbows to hips' not 'hands to chest'. This engages your lats far more effectively.",
        },
        {
            "name": "Seated Cable Row",
            "muscle": "Mid-Back · Lats · Rear Delts",
            "minutes": 14,
            "sets_reps": "3 sets × 10–12 reps",
            "equipment": "Cable Row Station, V-Bar or Rope",
            "difficulty": "Beginner",
            "steps": [
                "Sit with feet on the platform, slight bend in knees, back straight",
                "Grip the handle and sit tall — don't lean back excessively",
                "Pull handle toward your lower ribcage, leading with elbows",
                "Squeeze shoulder blades together firmly at the end of the pull",
                "Extend arms back out in a slow, controlled 3-second return",
            ],
            "tip": "Your torso should barely move. If you're rocking back and forth, reduce the weight.",
        },
        {
            "name": "Dumbbell Bicep Curl",
            "muscle": "Biceps",
            "minutes": 10,
            "sets_reps": "3 sets × 12 reps",
            "equipment": "Dumbbells",
            "difficulty": "Beginner",
            "steps": [
                "Stand with dumbbells at your sides, palms facing forward",
                "Curl both dumbbells up toward your shoulders simultaneously",
                "Squeeze biceps hard at the top — hold 1 second",
                "Lower slowly over 2–3 seconds back to start",
                "Don't swing your back or use momentum — control is everything",
            ],
            "tip": "You can also alternate arms for better mind-muscle connection. NEVER swing your back!",
        },
        {
            "name": "Cable Face Pull",
            "muscle": "Rear Delts · Rotator Cuff",
            "minutes": 10,
            "sets_reps": "3 sets × 15 reps",
            "equipment": "Cable Machine, Rope Attachment",
            "difficulty": "Beginner",
            "steps": [
                "Set the pulley at face height, attach the rope",
                "Grip the rope with thumbs pointing toward you, step back",
                "Pull the rope toward your face, flaring elbows out to the sides",
                "Separate the rope at the end, squeezing rear delts and rotator cuffs",
                "Return slowly to the start position",
            ],
            "tip": "The #1 shoulder health exercise. Light weight, high reps, always. Neglecting this leads to injuries.",
        },
        {
            "name": "Cool Down & Stretching",
            "muscle": "Back, Shoulders & Arms",
            "minutes": 8,
            "sets_reps": "8 min",
            "equipment": "Exercise Mat",
            "difficulty": "Beginner",
            "steps": [
                "Child's pose — 60 seconds to open up lats",
                "Cross-body shoulder stretch: 30 seconds each arm",
                "Doorway chest/bicep stretch: 30 seconds each side",
                "Seated spinal twist: 30 seconds each direction",
            ],
            "tip": "A few minutes of cool-down stretching after a pull session massively reduces next-day soreness.",
        },
    ],

    "Lower B": [
        {
            "name": "Bike Warm-Up",
            "muscle": "Legs & Cardiovascular",
            "minutes": 10,
            "sets_reps": "10 min steady",
            "equipment": "Stationary Bike",
            "difficulty": "Beginner",
            "steps": [
                "Set resistance to a comfortable level (around level 3–5)",
                "Pedal at 60–80 RPM for the first 5 minutes",
                "Increase resistance slightly for the final 5 minutes",
                "Finish with 1 minute easy to prepare for lifting",
            ],
            "tip": "The bike warms up your quads, hamstrings and hips perfectly before leg day.",
        },
        {
            "name": "Conventional Deadlift",
            "muscle": "Hamstrings · Glutes · Back · Full Body",
            "minutes": 20,
            "sets_reps": "3 sets × 6–8 reps",
            "equipment": "Barbell, Weight Plates",
            "difficulty": "Intermediate",
            "steps": [
                "Bar over mid-foot, stand hip-width apart, grip just outside legs",
                "Hinge down to grab bar: flatten back, chest up, hips above knees",
                "Take a big breath into your belly, brace your core firmly",
                "Push the floor away with your legs to lift — bar stays close to your body",
                "Lock out at the top: stand tall, hips fully extended, glutes squeezed",
                "Hinge back down with control, resetting your position each rep",
            ],
            "tip": "The king of all exercises. Ask a gym staff member to check your form on your first session — it's worth it.",
        },
        {
            "name": "Walking Lunges",
            "muscle": "Quads · Glutes · Balance",
            "minutes": 12,
            "sets_reps": "3 sets × 10 reps each leg",
            "equipment": "Bodyweight or Dumbbells",
            "difficulty": "Beginner",
            "steps": [
                "Stand tall, step forward with one leg into a wide lunge",
                "Lower your back knee toward the floor — don't let it slam down",
                "Front knee should stay directly above (not past) your toes",
                "Push off your front foot and step forward with the other leg",
                "Continue walking forward for 10 steps per leg",
            ],
            "tip": "Start with bodyweight before grabbing dumbbells. A long stride keeps stress off the knee.",
        },
        {
            "name": "Leg Extension Machine",
            "muscle": "Quads (Isolation)",
            "minutes": 10,
            "sets_reps": "3 sets × 12 reps",
            "equipment": "Leg Extension Machine",
            "difficulty": "Beginner",
            "steps": [
                "Sit with your back against the pad, adjust so knees align with machine pivot",
                "Position the shin pad just above your feet",
                "Extend your legs upward until almost straight",
                "Hold and squeeze your quads for 1 full second at the top",
                "Lower slowly over 3 seconds — do NOT drop the weight",
            ],
            "tip": "This is an isolation exercise — medium weight with maximum squeeze beats heavy weight with no squeeze.",
        },
        {
            "name": "Standing Calf Raise",
            "muscle": "Calves",
            "minutes": 8,
            "sets_reps": "3 sets × 15–20 reps",
            "equipment": "Calf Raise Machine or Step",
            "difficulty": "Beginner",
            "steps": [
                "Stand on the edge of a step or plate with heels hanging off",
                "Rise up on your toes as high as possible",
                "Hold at the top for 1 full second — feel the contraction",
                "Lower heels BELOW the step level for a full stretch at the bottom",
                "Don't bounce — each rep should be fully controlled",
            ],
            "tip": "Calves love high reps and slow, full-range movements. Bouncing up and down does nothing!",
        },
        {
            "name": "Cool Down & Stretching",
            "muscle": "Legs, Glutes & Lower Back",
            "minutes": 10,
            "sets_reps": "10 min",
            "equipment": "Exercise Mat",
            "difficulty": "Beginner",
            "steps": [
                "Standing quad stretch: 30 seconds each leg",
                "Lying glute stretch (figure-four): 45 seconds each side",
                "Downward dog calf stretch: 45 seconds each leg",
                "Child's pose for lower back: 60 seconds",
            ],
            "tip": "Your legs carry you everywhere — give them the care they deserve after a tough session.",
        },
    ],

    # ── GENERAL FITNESS ───────────────────────────────────────────────────────

    "Full Body Strength": [
        {
            "name": "Cardio Warm-Up",
            "muscle": "Full Body",
            "minutes": 8,
            "sets_reps": "8 min",
            "equipment": "Treadmill or Bike",
            "difficulty": "Beginner",
            "steps": [
                "5 minutes on treadmill at brisk walking or light jog",
                "10 × arm circles each direction",
                "10 × bodyweight squats",
                "10 × walking lunges",
            ],
            "tip": "A general warm-up for full body days should include both lower and upper body movements.",
        },
        {
            "name": "Goblet Squat",
            "muscle": "Quads · Glutes · Core",
            "minutes": 12,
            "sets_reps": "3 sets × 12 reps",
            "equipment": "Dumbbell or Kettlebell",
            "difficulty": "Beginner",
            "steps": [
                "Hold a dumbbell vertically at your chest with both hands",
                "Feet shoulder-width apart, toes turned slightly out",
                "Squat deep — the dumbbell keeps your chest upright naturally",
                "Drive through your heels to stand back up",
            ],
            "tip": "The goblet squat is the best teaching tool for squat mechanics. Master this before moving to a barbell.",
        },
        {
            "name": "Dumbbell Romanian Deadlift",
            "muscle": "Hamstrings · Glutes",
            "minutes": 12,
            "sets_reps": "3 sets × 10 reps",
            "equipment": "Dumbbells",
            "difficulty": "Beginner",
            "steps": [
                "Hold dumbbells in front of thighs, stand hip-width apart",
                "Hinge forward at the hips, pushing them backward",
                "Lower dumbbells along your legs until you feel a hamstring stretch",
                "Drive hips forward to return upright, squeezing glutes at the top",
            ],
            "tip": "Keep the dumbbells as close to your legs as possible throughout — they should almost brush your shins.",
        },
        {
            "name": "Dumbbell Push Press",
            "muscle": "Shoulders · Triceps · Legs",
            "minutes": 12,
            "sets_reps": "3 sets × 10 reps",
            "equipment": "Dumbbells",
            "difficulty": "Beginner",
            "steps": [
                "Hold dumbbells at shoulder height, palms facing in",
                "Dip slightly at the knees, then explosively drive dumbbells overhead",
                "Fully extend arms at the top, stand tall",
                "Lower back to shoulders in a slow, controlled manner",
            ],
            "tip": "The slight leg drive makes this easier than a strict press — great for beginners building shoulder strength.",
        },
        {
            "name": "Seated Cable Row",
            "muscle": "Back · Biceps",
            "minutes": 12,
            "sets_reps": "3 sets × 12 reps",
            "equipment": "Cable Row Station",
            "difficulty": "Beginner",
            "steps": [
                "Sit tall at the cable row station, feet on platform",
                "Grip the handle and pull toward your lower ribcage",
                "Squeeze shoulder blades together at the end of each pull",
                "Extend arms slowly back to the start position",
            ],
            "tip": "Full body days benefit from compound pulling movements — this hits your back and biceps simultaneously.",
        },
        {
            "name": "Plank Hold",
            "muscle": "Core · Full Body Stability",
            "minutes": 8,
            "sets_reps": "3 sets × 30–60 seconds",
            "equipment": "Exercise Mat",
            "difficulty": "Beginner",
            "steps": [
                "Get into a push-up position, rest on forearms instead of hands",
                "Body should form a straight line from head to heels",
                "Engage your core, squeeze your glutes, breathe normally",
                "Hold for 30 seconds (beginner) or 60 seconds (intermediate)",
            ],
            "tip": "Quality beats duration. A solid 30-second plank beats a sagging 90-second one every time.",
        },
        {
            "name": "Cool Down",
            "muscle": "Full Body",
            "minutes": 8,
            "sets_reps": "8 min",
            "equipment": "Exercise Mat",
            "difficulty": "Beginner",
            "steps": [
                "Cat-cow spinal stretch: 60 seconds",
                "Hip flexor kneeling lunge stretch: 30 seconds each side",
                "Chest doorway stretch: 30 seconds",
                "Child's pose: 60 seconds",
            ],
            "tip": "Full body workouts are demanding. Take your cool-down seriously to recover faster.",
        },
    ],

    "Cardio & Core": [
        {
            "name": "Treadmill Intervals",
            "muscle": "Cardiovascular · Legs",
            "minutes": 20,
            "sets_reps": "10 × 1 min run / 1 min walk",
            "equipment": "Treadmill",
            "difficulty": "Beginner",
            "steps": [
                "Warm up 3 minutes at brisk walking pace",
                "Increase speed to a challenging jog for 1 minute",
                "Recover at walking pace for 1 minute",
                "Repeat 10 times, then cool down walking for 2 minutes",
            ],
            "tip": "Intervals burn far more calories than steady-state cardio in the same time.",
        },
        {
            "name": "Plank Variations",
            "muscle": "Core",
            "minutes": 10,
            "sets_reps": "3 rounds",
            "equipment": "Exercise Mat",
            "difficulty": "Beginner",
            "steps": [
                "Standard plank hold: 30 seconds",
                "Left side plank: 20 seconds",
                "Right side plank: 20 seconds",
                "Rest 30 seconds, then repeat for 3 total rounds",
            ],
            "tip": "Side planks target your obliques — the muscles that give you a defined waist.",
        },
        {
            "name": "Dead Bug",
            "muscle": "Deep Core Stabilisers",
            "minutes": 8,
            "sets_reps": "3 sets × 10 reps each side",
            "equipment": "Exercise Mat",
            "difficulty": "Beginner",
            "steps": [
                "Lie on your back, arms pointing up, knees at 90° above hips",
                "Slowly lower your right arm behind your head and left leg toward the floor simultaneously",
                "Keep your lower back pressed into the mat throughout",
                "Return to start, then repeat on the opposite side",
            ],
            "tip": "One of the safest and most effective core exercises. It teaches your spine to stay stable during limb movement.",
        },
        {
            "name": "Mountain Climbers",
            "muscle": "Core · Cardio · Shoulders",
            "minutes": 8,
            "sets_reps": "3 sets × 30 seconds",
            "equipment": "None (Floor Space)",
            "difficulty": "Beginner",
            "steps": [
                "Get into a push-up position, wrists under shoulders",
                "Drive your right knee toward your chest, then switch legs rapidly",
                "Keep your hips level — don't let them rise or sag",
                "Move as fast as you can while maintaining good form",
            ],
            "tip": "Mountain climbers double as cardio and core work. They're harder than they look — pace yourself initially.",
        },
        {
            "name": "Stretching & Cool Down",
            "muscle": "Full Body",
            "minutes": 8,
            "sets_reps": "8 min",
            "equipment": "Exercise Mat",
            "difficulty": "Beginner",
            "steps": [
                "Lying knee-to-chest stretch: 30 seconds each side",
                "Spinal twist on floor: 30 seconds each direction",
                "Cobra pose for abs: 30 seconds",
                "Happy baby pose for hips: 60 seconds",
            ],
            "tip": "After cardio and core work, your spine needs some love. Don't skip the cool-down stretches.",
        },
    ],

    "Cardio & Flexibility": [
        {
            "name": "Light Cardio",
            "muscle": "Cardiovascular",
            "minutes": 20,
            "sets_reps": "20 min steady",
            "equipment": "Treadmill, Bike or Elliptical",
            "difficulty": "Beginner",
            "steps": [
                "Choose your favourite cardio machine",
                "Set to a moderate pace — conversational effort",
                "Maintain consistent rhythm for 20 minutes",
                "Last 2 minutes: reduce pace to cool down",
            ],
            "tip": "Finish-of-week cardio should feel energising, not exhausting. Keep it moderate.",
        },
        {
            "name": "Full Body Flexibility Routine",
            "muscle": "Full Body",
            "minutes": 25,
            "sets_reps": "Hold each 45–60 seconds",
            "equipment": "Yoga Mat",
            "difficulty": "Beginner",
            "steps": [
                "Standing forward fold: 60 seconds",
                "Seated butterfly stretch: 60 seconds",
                "Hip flexor kneeling lunge: 45 seconds each side",
                "Chest opener with arms clasped behind: 45 seconds",
                "Lying spinal twist: 45 seconds each side",
                "Child's pose to finish: 90 seconds",
            ],
            "tip": "End-of-week flexibility work compounds over months. Consistency is more important than intensity here.",
        },
    ],

    "Active Recovery": [
        {
            "name": "Active Recovery Walk",
            "muscle": "Cardiovascular — Light",
            "minutes": 20,
            "sets_reps": "20 min easy",
            "equipment": "None (Outdoors or Treadmill)",
            "difficulty": "Beginner",
            "steps": [
                "Walk at a comfortable, relaxed pace",
                "Focus on deep, slow breathing",
                "Swing arms naturally, stand tall",
                "Can be done outdoors for added mental benefit",
            ],
            "tip": "Active recovery keeps blood flowing to your muscles, clearing waste products and speeding up repair.",
        },
        {
            "name": "Full Body Mobility",
            "muscle": "Full Body Joints",
            "minutes": 20,
            "sets_reps": "Continuous flow",
            "equipment": "Yoga Mat, Foam Roller (optional)",
            "difficulty": "Beginner",
            "steps": [
                "Foam roll major muscle groups: 60 seconds each area",
                "Hip 90-90 stretch: 45 seconds each side",
                "World's greatest stretch: 5 reps each side",
                "Thread-the-needle thoracic rotation: 30 seconds each side",
                "Cat-cow spinal flow: 10 slow reps",
            ],
            "tip": "Saturday mobility sessions compound over months into exceptional flexibility. Make this a non-negotiable habit.",
        },
    ],

    # ── WEIGHT LOSS ───────────────────────────────────────────────────────────

    "HIIT & Circuits": [
        {
            "name": "Circuit Warm-Up",
            "muscle": "Full Body",
            "minutes": 5,
            "sets_reps": "1 round easy",
            "equipment": "None",
            "difficulty": "Beginner",
            "steps": [
                "20 × jumping jacks",
                "10 × arm circles each direction",
                "10 × bodyweight squats",
                "10 × hip hinges",
            ],
            "tip": "HIIT sessions demand a proper warm-up — your heart rate and muscles need to be ready before high-intensity work.",
        },
        {
            "name": "HIIT Circuit",
            "muscle": "Full Body — Fat Burning",
            "minutes": 25,
            "sets_reps": "4 rounds, 40s work / 20s rest",
            "equipment": "None or Dumbbells",
            "difficulty": "Intermediate",
            "steps": [
                "Burpees — 40 seconds at max effort",
                "Dumbbell squat to press — 40 seconds",
                "Jump lunges (or walking lunges) — 40 seconds",
                "Push-ups — 40 seconds",
                "Rest 90 seconds between complete rounds",
            ],
            "tip": "Push as hard as you can during the 40-second work intervals — that's where the fat burning happens.",
        },
        {
            "name": "Core Finisher",
            "muscle": "Abs · Obliques",
            "minutes": 8,
            "sets_reps": "2 rounds",
            "equipment": "Exercise Mat",
            "difficulty": "Beginner",
            "steps": [
                "Crunches: 20 reps",
                "Bicycle crunches: 20 reps each side",
                "Leg raises: 15 reps",
                "30-second plank to finish",
            ],
            "tip": "Finish HIIT sessions with a core finisher — your abs are pre-fatigued, making this extra effective.",
        },
        {
            "name": "Cool Down",
            "muscle": "Full Body",
            "minutes": 8,
            "sets_reps": "8 min",
            "equipment": "Exercise Mat",
            "difficulty": "Beginner",
            "steps": [
                "Walk slowly for 2 minutes to lower heart rate",
                "Seated forward fold: 60 seconds",
                "Pigeon pose: 45 seconds each side",
                "Child's pose: 60 seconds",
            ],
            "tip": "After intense HIIT, your heart rate needs to come down gradually. Never sit or lie down immediately.",
        },
    ],

    "Strength & Cardio": [
        {
            "name": "5-Minute Cardio Warm-Up",
            "muscle": "Full Body",
            "minutes": 5,
            "sets_reps": "5 min",
            "equipment": "Treadmill or Bike",
            "difficulty": "Beginner",
            "steps": [
                "Light jog or brisk walk for 5 minutes",
                "Get heart rate up to about 50–60% of your max",
                "Breathe through your nose if possible",
                "Finish with 30 seconds at a faster pace",
            ],
            "tip": "A brief cardio warm-up prepares your cardiovascular system for the mixed demands of this session.",
        },
        {
            "name": "Dumbbell Full Body Circuit",
            "muscle": "Full Body",
            "minutes": 20,
            "sets_reps": "3 rounds × 12 reps each",
            "equipment": "Dumbbells",
            "difficulty": "Beginner",
            "steps": [
                "Dumbbell squat × 12 reps",
                "Dumbbell bent-over row × 12 reps",
                "Dumbbell push press × 12 reps",
                "Dumbbell Romanian deadlift × 12 reps",
                "Rest 60–90 seconds between rounds",
            ],
            "tip": "Move through each exercise back-to-back with minimal rest for a combined strength + cardio effect.",
        },
        {
            "name": "20-Min Moderate Cardio",
            "muscle": "Cardiovascular",
            "minutes": 20,
            "sets_reps": "20 min steady state",
            "equipment": "Treadmill, Bike or Elliptical",
            "difficulty": "Beginner",
            "steps": [
                "Choose a machine and set to moderate resistance/speed",
                "Work at 60–70% of max heart rate — you should be able to talk",
                "Maintain consistent pace throughout",
                "Last 2 minutes: reduce intensity to cool down",
            ],
            "tip": "The 'fat burning zone' is 60–70% of your max HR. Formula: 220 − your age = max heart rate.",
        },
        {
            "name": "Cool Down & Stretch",
            "muscle": "Full Body",
            "minutes": 8,
            "sets_reps": "8 min",
            "equipment": "Exercise Mat",
            "difficulty": "Beginner",
            "steps": [
                "Standing quad stretch: 30 seconds each leg",
                "Chest stretch against wall: 30 seconds",
                "Seated hamstring stretch: 60 seconds",
                "Deep breathing: 5 slow breaths",
            ],
            "tip": "Combining strength and cardio is very demanding. Prioritise sleep and protein intake on these days.",
        },
    ],

    "Light Cardio": [
        {
            "name": "Steady-State Cardio Session",
            "muscle": "Cardiovascular",
            "minutes": 30,
            "sets_reps": "30 min continuous",
            "equipment": "Treadmill, Bike, or Elliptical",
            "difficulty": "Beginner",
            "steps": [
                "Choose your preferred cardio machine",
                "Set to a comfortable, moderate pace — conversational effort",
                "Maintain consistent effort for 30 minutes",
                "Focus on good posture and steady breathing throughout",
            ],
            "tip": "Light cardio on active recovery days keeps your metabolism up without stressing your muscles.",
        },
        {
            "name": "Gentle Full Body Stretch",
            "muscle": "Full Body Flexibility",
            "minutes": 15,
            "sets_reps": "15 min",
            "equipment": "Exercise Mat",
            "difficulty": "Beginner",
            "steps": [
                "Neck rolls: 30 seconds each direction",
                "Seated forward fold: 60 seconds",
                "Lying glute stretch (figure-four): 45 seconds each side",
                "Child's pose: 60 seconds",
                "Cobra stretch: 30 seconds × 2",
            ],
            "tip": "Saturday is your chance to improve flexibility while the week's training is still fresh in your muscles.",
        },
    ],

    # ── ENDURANCE & CARDIO ────────────────────────────────────────────────────

    "Steady-State Cardio": [
        {
            "name": "Steady-State Cardio",
            "muscle": "Cardiovascular · Endurance",
            "minutes": 40,
            "sets_reps": "40 min at zone 2",
            "equipment": "Treadmill, Bike or Elliptical",
            "difficulty": "Beginner",
            "steps": [
                "Warm up 5 minutes at easy pace",
                "Settle into Zone 2 — 60–70% max HR, conversational pace",
                "Maintain this for 30 minutes without stopping",
                "Cool down 5 minutes at easy walking pace",
            ],
            "tip": "Zone 2 cardio builds your aerobic base — the foundation of all endurance fitness. It should feel almost too easy.",
        },
        {
            "name": "Post-Cardio Stretch",
            "muscle": "Legs & Hips",
            "minutes": 10,
            "sets_reps": "10 min",
            "equipment": "Exercise Mat",
            "difficulty": "Beginner",
            "steps": [
                "Standing calf stretch: 30 seconds each",
                "Hip flexor kneeling stretch: 30 seconds each",
                "IT band stretch: 30 seconds each side",
                "Child's pose: 60 seconds",
            ],
            "tip": "After long cardio sessions, your hip flexors and calves are especially tight. Give them focused attention.",
        },
    ],

    "Interval Training": [
        {
            "name": "Speed Intervals",
            "muscle": "Cardiovascular · Legs",
            "minutes": 30,
            "sets_reps": "8 × 2 min hard / 2 min easy",
            "equipment": "Treadmill or Outdoor Track",
            "difficulty": "Intermediate",
            "steps": [
                "Warm up 5 minutes at easy jog",
                "Run at 80–85% max HR for 2 minutes (hard effort)",
                "Recover at 50% max HR for 2 minutes (easy jog or walk)",
                "Repeat 8 times, then cool down 5 minutes easy",
            ],
            "tip": "Intervals are the most time-efficient way to build cardiovascular fitness. Push hard during the effort intervals.",
        },
        {
            "name": "Stretching",
            "muscle": "Full Body",
            "minutes": 10,
            "sets_reps": "10 min",
            "equipment": "Exercise Mat",
            "difficulty": "Beginner",
            "steps": [
                "Seated hamstring stretch: 60 seconds",
                "Quad stretch standing: 30 seconds each",
                "Hip flexor stretch kneeling: 30 seconds each",
                "Spinal twist: 30 seconds each direction",
            ],
            "tip": "Never skip stretching after intervals — your muscles have been working hard at speed and need to lengthen back out.",
        },
    ],

    "Cross Training": [
        {
            "name": "Cross-Training Circuit",
            "muscle": "Full Body — Active Recovery",
            "minutes": 35,
            "sets_reps": "3 rotations",
            "equipment": "Various",
            "difficulty": "Beginner",
            "steps": [
                "10 min swimming or aqua jogging (low-impact)",
                "10 min on the rowing machine at moderate pace",
                "10 min cycling on the stationary bike",
                "5 min cool down walking",
            ],
            "tip": "Cross training gives your primary cardio muscles a break while still working your cardiovascular system.",
        },
        {
            "name": "Gentle Stretching",
            "muscle": "Full Body",
            "minutes": 10,
            "sets_reps": "10 min",
            "equipment": "Exercise Mat",
            "difficulty": "Beginner",
            "steps": [
                "Cat-cow stretch: 60 seconds",
                "Chest opener stretch: 30 seconds",
                "Seated forward fold: 60 seconds",
                "Lying spinal twist: 30 seconds each side",
            ],
            "tip": "Keep this session easy — cross training days are about active recovery, not pushing your limits.",
        },
    ],

    "Long Cardio Session": [
        {
            "name": "Long Endurance Session",
            "muscle": "Cardiovascular",
            "minutes": 60,
            "sets_reps": "60 min zone 2–3",
            "equipment": "Treadmill, Bike or Elliptical",
            "difficulty": "Intermediate",
            "steps": [
                "Warm up 10 minutes at easy pace",
                "Settle into zone 2–3 (65–75% max HR) for 40 minutes",
                "Final 5 minutes: push to zone 3 (75–80% max HR)",
                "Cool down 5 minutes easy",
            ],
            "tip": "Long sessions build the aerobic base that makes everything else easier. Fuel properly beforehand.",
        },
        {
            "name": "Full Body Cool Down",
            "muscle": "Full Body",
            "minutes": 10,
            "sets_reps": "10 min",
            "equipment": "Exercise Mat",
            "difficulty": "Beginner",
            "steps": [
                "Walk 3 minutes to lower heart rate gradually",
                "Full body stretching circuit: legs, hips, back, shoulders",
                "Deep breathing: 5 slow, controlled breaths",
                "Foam rolling if available: 2 minutes total",
            ],
            "tip": "After an hour of cardio, a thorough cool-down is essential. Hydrate well and eat a recovery meal within 30 minutes.",
        },
    ],

    "Recovery Cardio": [
        {
            "name": "Easy Recovery Walk/Jog",
            "muscle": "Cardiovascular — Light",
            "minutes": 25,
            "sets_reps": "25 min easy",
            "equipment": "Treadmill or Outdoors",
            "difficulty": "Beginner",
            "steps": [
                "Walk or very light jog at 40–50% max HR",
                "Conversation should be completely easy at this pace",
                "Focus on good posture and relaxed breathing",
                "No pushing — this is about blood flow, not fitness gains",
            ],
            "tip": "Recovery cardio flushes lactic acid from your muscles and speeds up recovery. Resist the urge to push harder!",
        },
        {
            "name": "Mobility Work",
            "muscle": "Full Body",
            "minutes": 15,
            "sets_reps": "15 min",
            "equipment": "Exercise Mat, Foam Roller",
            "difficulty": "Beginner",
            "steps": [
                "Foam roll quads, hamstrings and calves: 60 seconds each",
                "Hip 90-90 stretch: 45 seconds each side",
                "Ankle circles: 20 each direction",
                "World's greatest stretch: 5 reps each side",
            ],
            "tip": "Recovery days and mobility work are where elite athletes separate themselves from amateurs.",
        },
    ],

    # ── FLEXIBILITY & MOBILITY ────────────────────────────────────────────────

    "Yoga Flow": [
        {
            "name": "Sun Salutation Flow",
            "muscle": "Full Body Flexibility",
            "minutes": 20,
            "sets_reps": "5 × full sun salutation",
            "equipment": "Yoga Mat",
            "difficulty": "Beginner",
            "steps": [
                "Mountain pose → Forward fold → Halfway lift",
                "Step back to plank → Lower to cobra/upward dog",
                "Push to downward dog → Hold 5 breaths",
                "Walk feet forward → Halfway lift → Forward fold → Mountain pose",
            ],
            "tip": "Sun salutations warm up your entire spine and connect movement with breath. Move slowly and intentionally.",
        },
        {
            "name": "Standing Balance Poses",
            "muscle": "Balance · Legs · Core",
            "minutes": 15,
            "sets_reps": "30–60 seconds each pose",
            "equipment": "Yoga Mat",
            "difficulty": "Beginner",
            "steps": [
                "Tree pose: 30 seconds each leg",
                "Warrior I: 45 seconds each side",
                "Warrior II: 45 seconds each side",
                "Warrior III: 20 seconds each side",
            ],
            "tip": "Fix your gaze on a still point (drishti) to improve balance. It gets better quickly with consistent practice.",
        },
        {
            "name": "Floor Poses & Cool Down",
            "muscle": "Hips, Hamstrings & Lower Back",
            "minutes": 15,
            "sets_reps": "60 seconds each pose",
            "equipment": "Yoga Mat",
            "difficulty": "Beginner",
            "steps": [
                "Seated forward fold (Paschimottanasana): 60 seconds",
                "Butterfly pose: 60 seconds",
                "Supine spinal twist: 45 seconds each side",
                "Savasana (rest): 3 minutes",
            ],
            "tip": "Savasana is not optional! This is when your nervous system integrates all the benefits of the practice.",
        },
    ],

    "Mobility Drills": [
        {
            "name": "Joint Mobility Circuit",
            "muscle": "Full Body Joints",
            "minutes": 25,
            "sets_reps": "2 rounds × 10 reps each",
            "equipment": "None",
            "difficulty": "Beginner",
            "steps": [
                "Neck: slow circles 10 each direction",
                "Shoulders: arm circles 10 forward, 10 backward",
                "Hips: hip circles 10 each direction",
                "Ankles: circles 10 each direction, then flexion/extension",
            ],
            "tip": "Joint mobility training increases synovial fluid in your joints — this is what keeps them healthy long-term.",
        },
        {
            "name": "Thoracic Mobility",
            "muscle": "Upper Back & Spine",
            "minutes": 15,
            "sets_reps": "2 rounds",
            "equipment": "Foam Roller, Mat",
            "difficulty": "Beginner",
            "steps": [
                "Thoracic extension over foam roller: 2 minutes",
                "Thread-the-needle stretch: 45 seconds each side",
                "Cat-cow: 10 slow reps",
                "Open book rotation: 10 each side",
            ],
            "tip": "Most people have poor thoracic mobility from sitting at desks. This will transform your posture over time.",
        },
    ],

    "Deep Stretch": [
        {
            "name": "Full Body Deep Stretch",
            "muscle": "All Major Muscle Groups",
            "minutes": 45,
            "sets_reps": "Hold each 60–90 seconds",
            "equipment": "Yoga Mat, Straps (optional)",
            "difficulty": "Beginner",
            "steps": [
                "Hip flexor kneeling lunge stretch: 90 seconds each",
                "Pigeon pose (glutes): 90 seconds each side",
                "Seated hamstring stretch with strap: 90 seconds",
                "Doorway chest stretch: 60 seconds",
                "Supine spinal twist: 60 seconds each side",
                "Child's pose: 2 minutes to finish",
            ],
            "tip": "Never force deep stretches. Breathe into areas of tension and allow the muscle to relax over 60–90 seconds.",
        },
    ],

    "Active Mobility": [
        {
            "name": "Active Mobility Flow",
            "muscle": "Full Body",
            "minutes": 40,
            "sets_reps": "Continuous flow",
            "equipment": "Yoga Mat",
            "difficulty": "Beginner",
            "steps": [
                "5 min foam rolling: target tight areas",
                "10 min joint circles: neck, shoulders, hips, ankles",
                "10 min yoga flow: sun salutations at slow pace",
                "10 min deep stretching: focus on areas worked this week",
                "5 min breathing: box breathing (4s in, 4s hold, 4s out, 4s hold)",
            ],
            "tip": "Saturday active mobility sessions compound over months into exceptional flexibility and joint health.",
        },
    ],
}
